Controllers/SubLedgersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BudgetPortal.Data;
using BudgetPortal.Entities;
using Microsoft.AspNetCore.Authorization;

namespace BudgetPortal.Controllers
{
    public class SubLedgersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<SubLedgersController> _logger;

        public SubLedgersController(ApplicationDbContext context, ILogger<SubLedgersController> logger)
        {
            _context = context;
            _logger = logger;
        }

        // GET: Ledgers
        [Authorize]
        public async Task<IActionResult> Index(String SubGroupid, String sortOrder)
        {
            //var applicationDbContext = _context.BudgetLedgers.Where (b=> (b.SubGroupNo).Equals(SubGroupid) ).Include(b => b.subGroups);

            var applicationDbContext = from b in _context.BudgetLedgers where(b.SubGroupNo.Equals(SubGroupid)) select b;
            ViewData["SubGroupNo"] = SubGroupid;
            var GroupNo = _context.BudgetSubGroups.Where(a=>a.SubGroupNo.Equals(SubGroupid)).Select(a=>a.GroupNo).FirstOrDefault();
            ViewData["GroupNo"] = GroupNo.ToString();

            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";

            switch (sortOrder)
            {
                case "Date":
                    applicationDbContext = applicationDbContext.OrderBy(s => s.CreatedDateTime);
                    break;
                case "date_desc":
                    applicationDbContext = applicationDbContext.OrderByDescending(s => s.CreatedDateTime);
                    break;
                default:
                    applicationDbContext = applicationDbContext.OrderBy(s => s.CreatedDateTime);
                    break;
            }

            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Ledgers/Details/5
        [Authorize]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.BudgetLedgers == null)
            {
                return NotFound();
            }

            var budgetLedgers = await _context.BudgetLedgers
                .Include(b => b.subGroups)
                .FirstOrDefaultAsync(m => m.LedgerNo == id);
            if (budgetLedgers == null)
            {
                return NotFound();
            }
            ViewData["SubGroupId"] = _context.BudgetLedgers.Where(b => b.LedgerNo == id).Select(b => b.SubGroupNo).FirstOrDefault();
            return View(budgetLedgers);
        }

        // GET: Ledgers/Create
        [Authorize]
        public IActionResult Create(String SubGroupid)
        {
            ViewData["SubGroupNo"] = new SelectList(_context.BudgetSubGroups, "SubGroupNo", "SubGroupNo", SubGroupid);
            ViewData["SubGroupID"] = SubGroupid;
            return View();
        }

        // POST: Ledgers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LedgerNo,LedgerName,SubGroupNo,CreatedDateTime")] BudgetSubLedgers budgetLedgers)
        {
            if (ModelState.IsValid)
            {
                _context.Add(budgetLedgers);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index),"Ledgers",new { SubGroupid  = budgetLedgers.SubGroupNo});
            }
            ViewData["SubGroupNo"] = new SelectList(_context.BudgetSubGroups, "SubGroupNo", "SubGroupNo", budgetLedgers.SubGroupNo);
            return View(budgetLedgers);
        }

        // GET: Ledgers/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.BudgetLedgers == null)
            {
                return NotFound();
            }

            var budgetLedgers = await _context.BudgetLedgers.FindAsync(id);
            if (budgetLedgers == null)
            {
                return NotFound();
            }
            ViewData["SubGroupId"] = _context.BudgetLedgers.Where(b => b.LedgerNo == id).Select(b => b.SubGroupNo).FirstOrDefault();
            ViewData["SubGroupNo"] = new SelectList(_context.BudgetSubGroups, "SubGroupNo", "SubGroupNo", budgetLedgers.SubGroupNo);
            return View(budgetLedgers);
        }

        // POST: Ledgers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("LedgerNo,LedgerName,SubGroupNo,CreatedDateTime")] BudgetSubLedgers budgetLedgers)
        {
            if (id != budgetLedgers.LedgerNo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(budgetLedgers);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BudgetLedgersExists(budgetLedgers.LedgerNo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                //return RedirectToAction(nameof(Index));
                return RedirectToAction(nameof(Index), "Ledgers", new { SubGroupid = budgetLedgers.SubGroupNo });
            }
            ViewData["SubGroupNo"] = new SelectList(_context.BudgetSubGroups, "SubGroupNo", "SubGroupNo", budgetLedgers.SubGroupNo);
            return View(budgetLedgers);
        }

        // GET: Ledgers/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.BudgetLedgers == null)
            {
                return NotFound();
            }

            var budgetLedgers = await _context.BudgetLedgers
                .Include(b => b.subGroups)
                .FirstOrDefaultAsync(m => m.LedgerNo == id);
            if (budgetLedgers == null)
            {
                return NotFound();
            }
            ViewData["SubGroupId"] = _context.BudgetLedgers.Where(b => b.LedgerNo == id).Select(b => b.SubGroupNo).FirstOrDefault();
            return View(budgetLedgers);
        }

        // POST: Ledgers/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.BudgetLedgers == null)
            {
                return Problem("Entity set 'ApplicationDbContext.BudgetLedgers'  is null.");
            }
            var budgetLedgers = await _context.BudgetLedgers.FindAsync(id);
            if (budgetLedgers != null)
            {
                _context.BudgetLedgers.Remove(budgetLedgers);
            }
            
            await _context.SaveChangesAsync();
            //return RedirectToAction(nameof(Index));
            return RedirectToAction(nameof(Index), "Ledgers", new { SubGroupid = budgetLedgers.SubGroupNo });
        }

        [Authorize]
        private bool BudgetLedgersExists(string id)
        {
          return (_context.BudgetLedgers?.Any(e => e.LedgerNo == id)).GetValueOrDefault();
        }
    }
}

Views/SubLedgers/Create.cshtml
@model BudgetPortal.Entities.BudgetSubLedgers

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Sub-Ledgers</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LedgerNo" class="control-label"></label>
                <input asp-for="LedgerNo" class="form-control" />
                <span asp-validation-for="LedgerNo" class="text-danger"></span>
            </div><br/>
            <div class="form-group">
                <label asp-for="LedgerName" class="control-label"></label>
                <input asp-for="LedgerName" class="form-control" />
                <span asp-validation-for="LedgerName" class="text-danger"></span>
            </div><br />
            <div class="form-group">
                <label asp-for="SubGroupNo" class="control-label"></label>
                <select asp-for="SubGroupNo" class="form-control" asp-items="ViewBag.SubGroupNo" readonly="readonly"></select>
            </div><br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div> <br />
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="SubLedgers" asp-route-SubGroupid="@ViewData["SubGroupID"]">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/SubLedgers/Delete.cshtml
@model BudgetPortal.Entities.BudgetSubLedgers

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BudgetLedgers</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LedgerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LedgerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.subGroups)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.subGroups.SubGroupNo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDateTime)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="LedgerNo" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" asp-controller="SubLedgers" asp-route-SubGroupid="@ViewData["SubGroupId"]">Back to List</a>
    </form>
</div>

Views/SubLedgers/Details.cshtml
@model BudgetPortal.Entities.BudgetSubLedgers

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>BudgetLedgers</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LedgerNo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LedgerNo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LedgerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LedgerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.subGroups)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.subGroups.SubGroupNo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDateTime)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.LedgerNo">Edit</a> |
    <a asp-action="Index" asp-controller="SubLedgers" asp-route-SubGroupid="@ViewData["SubGroupId"]">Back to List</a>
</div>

Views/SubLedgers/Edit.cshtml
@model BudgetPortal.Entities.BudgetSubLedgers

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Sub-Ledgers</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="LedgerNo" />
            
            <div class="form-group">
                <label asp-for="LedgerName" class="control-label"></label>
                <input asp-for="LedgerName" class="form-control" />
                <span asp-validation-for="LedgerName" class="text-danger"></span>
            </div><br />
            <div class="form-group">
                <label asp-for="SubGroupNo" class="control-label"></label>
                <select asp-for="SubGroupNo" class="form-control" asp-items="ViewBag.SubGroupNo"></select>
                <span asp-validation-for="SubGroupNo" class="text-danger"></span>
            </div><br />
            <div class="form-group">
                <label asp-for="CreatedDateTime" class="control-label"></label>
                <input asp-for="CreatedDateTime" class="form-control" readonly="readonly" />
                <span asp-validation-for="CreatedDateTime" class="text-danger"></span>
            </div><br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div><br />
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="SubLedgers" asp-route-SubGroupid="@ViewData["SubGroupId"]">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/SubLedgers/Index.cshtml
@model IEnumerable<BudgetPortal.Entities.BudgetSubLedgers>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Ledgers";
}

<h1>Sub-Ledgers</h1>

<p>
    <a asp-action="Create" asp-route-SubGroupid=@ViewData["SubGroupNo"]>Create New</a> |
    <a asp-action="Index" asp-controller="Ledgers" asp-route-Groupid="@ViewData["GroupNo"]">Back to Ledgers</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LedgerNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LedgerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.subGroups)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedDateTime)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LedgerNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LedgerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SubGroupNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDateTime)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.LedgerNo">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.LedgerNo">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.LedgerNo">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
<a asp-action="Index" asp-controller="Ledgers" asp-route-Groupid="@ViewData["GroupNo"]">Back to Ledgers</a>