Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BudgetPortal.Data;
using BudgetPortal.Entities;
using static System.Collections.Specialized.BitVector32;
using Microsoft.AspNetCore.Authorization;

namespace BudgetPortal.Controllers
{
    public class GroupsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<GroupsController> _logger;
        public GroupsController(ApplicationDbContext context, ILogger<GroupsController> logger)
        {
            _context = context;
            _logger = logger;
        }

        // GET: Groups
        [Authorize]
        public async Task<IActionResult> Index(int Sectionid, string sortOrder)
        {
            //var applicationDbContext = _context.BudgetGroups.Where(b =>b.SectionNo == Sectionid).Include(b => b.Sections);

            var applicationDbContext = from s in _context.BudgetGroups where(s.SectionNo == Sectionid) select s;

            ViewData["SecNo"] = Sectionid;
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
           
            switch (sortOrder)
            {
                case "Date":
                    applicationDbContext = applicationDbContext.OrderBy(s => s.CreatedDateTime);
                    break;
                case "date_desc":
                    applicationDbContext = applicationDbContext.OrderByDescending(s => s.CreatedDateTime);
                    break;
                default:
                    applicationDbContext = applicationDbContext.OrderBy(s => s.CreatedDateTime);
                    break;
            }
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Groups/Details/5
        [Authorize]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.BudgetGroups == null)
            {
                return NotFound();
            }

            var budgetGroups = await _context.BudgetGroups
                .Include(b => b.Sections)
                .FirstOrDefaultAsync(m => m.GroupNo == id);
            if (budgetGroups == null)
            {
                return NotFound();
            }
            ViewData["SectionId"] = _context.BudgetGroups.Where(b => b.GroupNo == id).Select(b => b.SectionNo).FirstOrDefault();
            return View(budgetGroups);
        }


        // GET: Groups/Create
        [Authorize]
        public IActionResult Create(int Sectionid)
        {
            ViewData["SectionNo"] = new SelectList(_context.BudgetSections, "SectionNo", "SectionNo", Sectionid);
            ViewData["SectionID"] = Sectionid;
            return View();                     
        }

        // POST: Groups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GroupNo,GroupName,SectionNo,CreatedDateTime")] BudgetGroups budgetGroups)
        {
            if (ModelState.IsValid)
            {
                _context.Add(budgetGroups);
                await _context.SaveChangesAsync();
                //Console.WriteLine("budgetGroups.SectionNo:" + budgetGroups.SectionNo);
                return RedirectToAction(nameof(Index), "Groups",new { sectionid = budgetGroups.SectionNo });
            }
            ViewData["SectionNo"] = new SelectList(_context.BudgetSections, "SectionNo", "SectionNo", budgetGroups.SectionNo);
            return View(budgetGroups);
        }

        // GET: Groups/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.BudgetGroups == null)
            {
                return NotFound();
            }

            var budgetGroups = await _context.BudgetGroups.FindAsync(id);
            if (budgetGroups == null)
            {
                return NotFound();
            }
            ViewData["SectionId"] = _context.BudgetGroups.Where(b => b.GroupNo == id).Select(b => b.SectionNo).FirstOrDefault();
            ViewData["SectionNo"] = new SelectList(_context.BudgetSections, "SectionNo", "SectionNo", budgetGroups.SectionNo);
            return View(budgetGroups);
        }

        // POST: Groups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("GroupNo,GroupName,SectionNo,CreatedDateTime")] BudgetGroups budgetGroups)
        {
            if (id != budgetGroups.GroupNo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(budgetGroups);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BudgetGroupsExists(budgetGroups.GroupNo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                //return RedirectToAction(nameof(Index));
                return RedirectToAction(nameof(Index), "Groups", new { sectionid = budgetGroups.SectionNo });
            }
            ViewData["SectionNo"] = new SelectList(_context.BudgetSections, "SectionNo", "SectionNo", budgetGroups.SectionNo);
            return View(budgetGroups);
        }

        // GET: Groups/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.BudgetGroups == null)
            {
                return NotFound();
            }

            var budgetGroups = await _context.BudgetGroups
                .Include(b => b.Sections)
                .FirstOrDefaultAsync(m => m.GroupNo == id);
            if (budgetGroups == null)
            {
                return NotFound();
            }
            ViewData["SectionId"] = _context.BudgetGroups.Where(b => b.GroupNo == id).Select(b => b.SectionNo).FirstOrDefault();
            return View(budgetGroups);
        }

        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.BudgetGroups == null)
            {
                return Problem("Entity set 'ApplicationDbContext.BudgetGroups'  is null.");
            }
            var budgetGroups = await _context.BudgetGroups.FindAsync(id);
            if (budgetGroups != null)
            {
                _context.BudgetGroups.Remove(budgetGroups);
            }
            
            await _context.SaveChangesAsync();
            //return RedirectToAction(nameof(Index));
            return RedirectToAction(nameof(Index), "Groups", new { sectionid = budgetGroups.SectionNo });
        }

        [Authorize]
        private bool BudgetGroupsExists(string id)
        {
          return (_context.BudgetGroups?.Any(e => e.GroupNo == id)).GetValueOrDefault();
        }
    }
}

Controllers/LedgersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BudgetPortal.Data;
using BudgetPortal.Entities;
using System.Text.RegularExpressions;
using static System.Collections.Specialized.BitVector32;
using Microsoft.AspNetCore.Authorization;

namespace BudgetPortal.Controllers
{
    public class LedgersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<LedgersController> _logger;
        public LedgersController(ApplicationDbContext context, ILogger<LedgersController> logger)
        {
            _context = context;
            _logger = logger;
        }

        // GET: SubGroups
        [Authorize]
        public async Task<IActionResult> Index(String Groupid, String sortOrder)
        {
            //var applicationDbContext = _context.BudgetSubGroups.Where(b => (b.GroupNo).Equals(Groupid)).Include(b => b.groups);

            var applicationDbContext = from b in _context.BudgetSubGroups where((b.GroupNo).Equals(Groupid)) select b;

            ViewData["GroupNo"] = Groupid;
            var SectionNo = _context.BudgetGroups.Where (a => a.GroupNo.Equals(Groupid)).Select (a => a.SectionNo).FirstOrDefault();
            ViewData["SectionNo"] = SectionNo;

            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
           
            switch (sortOrder)
            {
                case "Date":
                    applicationDbContext = applicationDbContext.OrderBy(s => s.CreatedDateTime);
                    break;
                case "date_desc":
                    applicationDbContext = applicationDbContext.OrderByDescending(s => s.CreatedDateTime);
                    break;
                default:
                    applicationDbContext = applicationDbContext.OrderBy(s => s.CreatedDateTime);
                    break;
            }

            return View(await applicationDbContext.ToListAsync());
        }

        // GET: SubGroups/Details/5
        [Authorize]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.BudgetSubGroups == null)
            {
                return NotFound();
            }

            var budgetSubGroups = await _context.BudgetSubGroups
                .Include(b => b.groups)
                .FirstOrDefaultAsync(m => m.SubGroupNo == id);
            if (budgetSubGroups == null)
            {
                return NotFound();
            }
            ViewData["GroupId"] = _context.BudgetSubGroups.Where(b => b.SubGroupNo == id).Select(b => b.GroupNo).FirstOrDefault();
            return View(budgetSubGroups);
        }

        // GET: SubGroups/Create
        [Authorize]
        public IActionResult Create(String Groupid)
        {
            ViewData["GroupNo"] = new SelectList(_context.BudgetGroups, "GroupNo", "GroupNo", Groupid);
            ViewData["GroupID"] = Groupid;
            return View();
        }

        // POST: SubGroups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SubGroupNo,subGroupName,GroupNo,RequireInput,CreatedDateTime")] BudgetLedgers budgetSubGroups)
        {
            if (ModelState.IsValid)
            {
                _context.Add(budgetSubGroups);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index),"SubGroups", new { Groupid = budgetSubGroups.GroupNo });
            }
            ViewData["GroupNo"] = new SelectList(_context.BudgetGroups, "GroupNo", "GroupNo", budgetSubGroups.GroupNo);
            
            return View(budgetSubGroups);
        }

        // GET: SubGroups/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.BudgetSubGroups == null)
            {
                return NotFound();
            }

            var budgetSubGroups = await _context.BudgetSubGroups.FindAsync(id);
            if (budgetSubGroups == null)
            {
                return NotFound();
            }
            ViewData["GroupId"] = _context.BudgetSubGroups.Where(b => b.SubGroupNo == id).Select(b => b.GroupNo).FirstOrDefault();
            ViewData["GroupNo"] = new SelectList(_context.BudgetGroups, "GroupNo", "GroupNo", budgetSubGroups.GroupNo);
            return View(budgetSubGroups);
        }

        // POST: SubGroups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("SubGroupNo,subGroupName,GroupNo,RequireInput,CreatedDateTime")] BudgetLedgers budgetSubGroups)
        {
            if (id != budgetSubGroups.SubGroupNo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(budgetSubGroups);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BudgetSubGroupsExists(budgetSubGroups.SubGroupNo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                //return RedirectToAction(nameof(Index));
                return RedirectToAction(nameof(Index), "SubGroups", new { Groupid = budgetSubGroups.GroupNo });
            }
            ViewData["GroupNo"] = new SelectList(_context.BudgetGroups, "GroupNo", "GroupNo", budgetSubGroups.GroupNo);
            return View(budgetSubGroups);
        }

        // GET: SubGroups/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.BudgetSubGroups == null)
            {
                return NotFound();
            }

            var budgetSubGroups = await _context.BudgetSubGroups
                .Include(b => b.groups)
                .FirstOrDefaultAsync(m => m.SubGroupNo == id);
            if (budgetSubGroups == null)
            {
                return NotFound();
            }
            ViewData["GroupId"] = _context.BudgetSubGroups.Where(b => b.SubGroupNo == id).Select(b => b.GroupNo).FirstOrDefault();

            return View(budgetSubGroups);
        }

        // POST: SubGroups/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.BudgetSubGroups == null)
            {
                return Problem("Entity set 'ApplicationDbContext.BudgetSubGroups'  is null.");
            }
            var budgetSubGroups = await _context.BudgetSubGroups.FindAsync(id);
            if (budgetSubGroups != null)
            {
                _context.BudgetSubGroups.Remove(budgetSubGroups);
            }
            
            await _context.SaveChangesAsync();
            //return RedirectToAction(nameof(Index));
            return RedirectToAction(nameof(Index), "SubGroups", new { Groupid = budgetSubGroups.GroupNo });
        }

        [Authorize]
        private bool BudgetSubGroupsExists(string id)
        {
          return (_context.BudgetSubGroups?.Any(e => e.SubGroupNo == id)).GetValueOrDefault();
        }
    }
}

Views/Groups/Create.cshtml
@model BudgetPortal.Entities.BudgetGroups

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>BudgetGroups</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="GroupNo" class="control-label"></label>
                <input asp-for="GroupNo" class="form-control" />
                <span asp-validation-for="GroupNo" class="text-danger"></span>
            </div><br />
            <div class="form-group">
                <label asp-for="GroupName" class="control-label"></label>
                <input asp-for="GroupName" class="form-control" />
                <span asp-validation-for="GroupName" class="text-danger"></span>
            </div><br />
            <div class="form-group">
                <label asp-for="SectionNo" class="control-label"></label>
                <select asp-for="SectionNo" class="form-control" asp-items="ViewBag.SectionNo" readonly="readonly"></select>
            </div><br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div><br />
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Groups" asp-route-Sectionid="@ViewData["SectionID"]">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Groups/Delete.cshtml
@model BudgetPortal.Entities.BudgetGroups

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BudgetGroups</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GroupName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GroupName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sections)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sections.SectionNo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDateTime)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="GroupNo" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" asp-controller="Groups" asp-route-Sectionid="@ViewData["SectionId"]">Back to List</a>
    </form>
</div>

Views/Groups/Details.cshtml
@model BudgetPortal.Entities.BudgetGroups

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Details";
}

<h1>Details</h1>


<div>
    <h4>Groups</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GroupNo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GroupNo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GroupName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GroupName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sections)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sections.SectionNo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDateTime)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.GroupNo">Edit</a> |
    <a asp-action="Index" asp-controller="Groups" asp-route-Sectionid="@ViewData["SectionId"]">Back to List</a>
</div>

Views/Groups/Edit.cshtml
@model BudgetPortal.Entities.BudgetGroups

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>BudgetGroups</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="GroupNo" />
           
            <div class="form-group">
                <label asp-for="GroupName" class="control-label"></label>
                <input asp-for="GroupName" class="form-control" />
                <span asp-validation-for="GroupName" class="text-danger"></span>
            </div><br />
            <div class="form-group">
                <label asp-for="SectionNo" class="control-label"></label>
                <select asp-for="SectionNo" class="form-control" asp-items="ViewBag.SectionNo"></select>
                <span asp-validation-for="SectionNo" class="text-danger"></span>
            </div><br />
            <div class="form-group">
                <label asp-for="CreatedDateTime" class="control-label"></label>
                <input asp-for="CreatedDateTime" class="form-control" readonly="readonly" />
                <span asp-validation-for="CreatedDateTime" class="text-danger"></span>
            </div><br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div><br />
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Groups" asp-route-Sectionid="@ViewData["SectionId"]">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Groups/Index.cshtml
@model IEnumerable<BudgetPortal.Entities.BudgetGroups>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Groups";
}

<h1>Groups</h1>

<p>
    
    <a asp-action="Create" asp-route-Sectionid=@ViewData["SecNo"] >Create New</a>|
    <a asp-action="Index" asp-controller="Sections">Back to Sections</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.GroupNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GroupName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sections)
            </th>
            <th>
               @Html.DisplayNameFor(model => model.CreatedDateTime)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
      @foreach (var item in Model) 
      {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.GroupNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GroupName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SectionNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDateTime)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.GroupNo">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.GroupNo">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.GroupNo">Delete</a> |
                <a asp-controller="Ledgers" asp-action="Index" asp-route-sortOrder="@ViewData["DateSortParm"]" asp-route-Groupid="@item.GroupNo">Add Ledgers</a>
            </td>
        </tr>
      }
    </tbody>
</table>

<a asp-action="Index" asp-controller="Sections">Back to Sections</a>